apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-09-08T07:08:21Z"
  generation: 1
  labels:
    app: sodbavekapp
  name: sodbavekapp
  namespace: default
  resourceVersion: "1384"
  uid: 5f61453f-25b9-43a4-a3cc-a4e418ae379c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sodbavekapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sodbavekapp
    spec:
      containers:
      - image: sodbaveka/sodbaveka-app:latest
        imagePullPolicy: Always
        name: sodbaveka-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-09-08T07:08:31Z"
    lastUpdateTime: "2021-09-08T07:08:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-09-08T07:08:21Z"
    lastUpdateTime: "2021-09-08T07:08:31Z"
    message: ReplicaSet "sodbavekapp-794766485d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-09-08T07:15:16Z"
  labels:
    app: sodbavekapp
  name: sodbavekapp
  namespace: default
  resourceVersion: "1914"
  uid: c242b2e1-caa5-4d6c-832a-15821f11b202
spec:
  clusterIP: 10.111.153.64
  clusterIPs:
  - 10.111.153.64
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 8080-80
    nodePort: 30968
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: sodbavekapp
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}