apiVersion: apps/v1
kind: Deployment
metadata:
  name: sodbavekapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sodbavekapp
  template:
    metadata:
      labels:
        app: sodbavekapp
        env: stage
    spec:
      containers:
      - name: sodbaveka-app
        image: sodbaveka/sodbaveka-app:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sodbavekapp
  labels:
    env: stage
spec:
  ports:
  - name: 8080-80
    nodePort: 30968
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: sodbavekapp
  sessionAffinity: None
  type: NodePort